from lib import *
A=card([h3('Adoption at the edge'),
  p('<b>Albania · “Diella”.</b> Chatbot on the e-Albania portal since Jan 2025; named “Minister of State for AI” on 11 Sep 2025, for procurement. Humans must approve its recommendations.',24),
  p('Rama: tenders will be “100% free of corruption”. Opposition: “a propaganda fantasy”. Its agency AKSHI is investigated over rigged tenders (over €40m seized); Diella’s own build was not among them.',24),
  p('<b>Romania · “Ion”.</b> A mirror-shaped AI adviser launched 1 Mar 2023 by the prime minister, built by volunteers, to relay citizens’ proposals. Early trouble: image copyright, unanswered privacy questions.',26)],gap=12,pad=28)
B=card([h3('Restriction at the other edge'),
  p('<b>Italy · ChatGPT.</b> Blocked in Mar 2023, lifted within a month after changes. Fined €15m on 20 Dec 2024. The Court of Rome annulled the fine on 18 Mar 2026; its legal ground was not verified here.',24),
  p('<b>DeepSeek, 2025.</b> Australia and Taiwan banned it on government devices (Feb); Italy blocked the app (Jan); the Czech Republic barred public administration (Jul); Germany asked Apple and Google to remove it from their app stores (Jun); South Korea suspended downloads.',24),
  p('Common reason: data security, especially storage in China.',24,MUTED)],gap=12,pad=28)
note=card([p('<b>No AI system holds a seat in any parliament in the sources reviewed.</b> Diella addressed Albania’s parliament on 18 Sep 2025, but as a cabinet “minister”, not a member. Ion is an adviser.',26)],bg=AMBER_L,border=AMBER_L,pad=24,gap=4,flex='none')
slide('extremes','Government · Extremes','At the extremes: an AI “minister”, and outright bans',
 stack([row([A,B]),note],gap=24),
 'Sources: Wikipedia on Diella; OCCRP; RFE/RL (2023); Reuters factbox on DeepSeek; Lewis Silkin; Wilson Sonsini.','9g',
 'Albania: Diella launched 19 Jan 2025 as a text assistant on eAlbania, developed by the National Agency for Information Society (AKSHI) with Microsoft and OpenAI technology; a presidential decree of 11 Sep 2025 made it "Minister of State for Artificial Intelligence" (first AI system in a cabinet role); it was to take over four procurement stages (drafting terms, eligibility criteria, price limits, document validity), with human experts approving all recommendations. Its parliamentary speech was on 18 Sep 2025; opposition leader Gazment Bardhi called it "a propaganda fantasy". On 26 Oct 2025 the prime minister said Diella was "pregnant with 83 children" (apparently AI assistants for members of parliament; documentation unclear). By mid-2025 the system had helped issue about 36,000 documents and serve about 1,000 services, but the outputs came from the eAlbania backend. OCCRP reports prosecutors investigating rigged tenders at AKSHI, with over 40 million euros of assets seized; these predate Diella and did not include her development; no one has been indicted. A Balkan Insight reality check of 14 Aug 2026 was blocked to us, so we do not report what Diella has achieved since. Romania: Ion was unveiled by Prime Minister Nicolae Ciuca on 1 Mar 2023 (RFE/RL), built by volunteer academics and industry experts; issues: an image used without permission, privacy questions, satirical reception. Restrictions: Italy\'s data protection authority blocked ChatGPT in March 2023, lifted in under a month, fined OpenAI 15 million euros on 20 Dec 2024 (of which 9m for unlawful processing, 5.68m for non-compliance with 2023 measures, 0.32m for late breach notice); the Court of Rome annulled the decision on 18 Mar 2026 (Wilson Sonsini); OpenAI had called the fine disproportionate. DeepSeek restrictions per a Reuters factbox: Australia (government devices, Feb 2025), Taiwan (Feb 2025), Italy (app blocked, Jan 2025), Czech Republic (public administration, Jul 2025), Germany (asked Apple and Google to remove the app, Jun 2025), Netherlands (civil servants), South Korea (new downloads suspended). The user asked about "an AI congress person"; we found no such case, only the minister and adviser above.',
 bg=PAPER)

def tl(date,title,txt,bg=CARD):
    return fixed([f'<p style="font-size:24px;font-weight:600;color:{TEAL}">{e(date)}</p>',f'<p style="font-size:28px;line-height:1.25;font-weight:600;color:{INK}">{e(title)}</p>',p(txt,24,MUTED)],0,bg=bg,pad=22).replace('width:0px;flex:none;','flex:1;')
cards=[tl('2 Feb 2025','Bans apply','Prohibited practices in force.'),
 tl('2 Aug 2025','General-purpose AI','Obligations for model providers apply.'),
 tl('27 Jul 2026','Omnibus in force','Published 24 Jul; agreed 6 May 2026.',AMBER_L),
 tl('2 Aug 2026','Transparency','Article 50 duties apply as scheduled.'),
 tl('2 Dec 2027','High-risk, stand-alone','Was 2 Aug 2026. Now 16 months later.',AMBER_L),
 tl('2 Aug 2028','High-risk, in products','Was 2 Aug 2027. Now 12 months later.',AMBER_L)]
body=stack([row(cards),
 grid([card([h3('What did not move'),p('Risk management, documentation, conformity checks and governance duties stay as written; only the dates shift.',28)],pad=28,gap=8),
       card([h3('What firms say'),p('69% of surveyed German industrial firms want help with the AI Act (IW Köln, 1,038 firms, Oct–Dec 2024).',28)],pad=28,gap=8)])],gap=28)
slide('reg','Regulation','The EU AI Act: bans first, the heaviest duties pushed to 2027–28',body,
 'Sources: Lewis Silkin (27 Jul 2026); Gibson Dunn (May 2026); IW Köln, IW-Report 2025.','9h',
 'The Digital Omnibus on AI: provisional political agreement on 6 May 2026, published in the Official Journal on 24 July 2026 and in force from 27 July 2026 (Lewis Silkin). New dates: Annex III stand-alone high-risk systems 2 December 2027 (previously 2 August 2026); Annex I systems embedded in regulated products 2 August 2028 (previously 2 August 2027). Unchanged: prohibited practices (Article 5, in force since 2 February 2025; a ban on non-consensual intimate imagery and child sexual abuse material was added, with a transitional period until 2 December 2026), general-purpose AI obligations (since 2 August 2025) and Article 50 transparency duties (2 August 2026, with a grace period to 2 December 2026 for machine-readable labelling of systems placed on the market before 2 August 2026). Other changes: AI literacy duty now shown by documentation; national sandboxes by 2 August 2027; simplified registration for self-assessed non-high-risk systems; support for small mid-caps. Fine amounts are not stated on this slide because we did not verify them in this research. IW Köln IW-Report 2025 (IW Future Panel wave 49, 1,038 firms, 16 Oct to 5 Dec 2024): 69% of firms want support in dealing with the AI Act; 66.3% of large firms and 35.6% of small firms use AI.',
 bg=PAPER2)
print('b4 ok')
