from lib import *
def fr(who,quote,ev,verd,vbg):
    return row([fixed([f'<p style="font-size:24px;font-weight:600;color:{TEAL}">{e(who)}</p>',p(quote,24)],560,pad=12),
      f'<div style="flex:1;background:{CARD};border:1px solid {LINE};border-radius:16px;padding:12px 24px;display:flex;flex-direction:column;justify-content:center">{p(ev,24)}</div>',
      f'<div style="width:300px;flex:none;background:{vbg};border-radius:16px;padding:18px 24px;display:flex;flex-direction:column;justify-content:center"><p style="font-size:26px;line-height:1.25;font-weight:600;color:{INK}">{e(verd)}</p></div>'])
rows=[
 fr('Amodei · Anthropic · Mar 2025','AI writes 90% of code within 3–6 months.','Anthropic: 70–90% company-wide (Jan 2026). Google: 75% of new code (Apr 2026). Self-measured; no industry figure.','Partly held, self-reported',AMBER_L),
 fr('Amodei · May 2025','Half of entry-level white-collar jobs gone in 1–5 years.','US unemployment 4.1% (Aug 2026). Stanford: exposed jobs for 22–25-year-olds 19% below peers, via fewer hires; no widespread displacement.','Too early; 10–20% unemployment off track',TEAL_L),
 fr('Altman · OpenAI · Jan 2025','First AI agents “may join the workforce” in 2025.','11% of organisations had agents in production (Deloitte). Karpathy, Feb 2026: coding agents “didn’t work before December”.','Mostly not in 2025 (“may”)',AMBER_L),
 fr('Zuckerberg · Meta · Jan–Apr 2025','AI “mid-level engineer” in 2025; half of development by AI in a year.','No Meta figure found. Jul 2026: agents had not progressed as fast as hoped (TechCrunch).','Not shown',AMBER_L),
 fr('Altman · OpenAI · Oct 2025','An automated AI research intern by Sep 2026.','OpenAI says it reached it, on its own definition. No outside check.','Held per OpenAI, unverified',TEAL_L),
]
slide('lead1','AI leaders’ forecasts','AI leaders’ forecasts against the evidence',stack(rows,gap=14),
 'Sources: CFR (10 Mar 2025); Axios (28 May 2025); Fortune (29 Jan 2026); Google (22 Apr 2026); BLS (4 Sep 2026); Stanford DEL (12 Aug 2026); OpenAI (Sep 2026).','A',
 'Scorecard of prominent forecasts by AI-industry leaders; verdicts are our reading of the cited evidence. (1) Amodei at CFR, 10 Mar 2025: "we will be there in three to six months, where AI is writing 90 percent of the code. And then in twelve months, we may be in a world where AI is writing essentially all of the code." Anthropic spokesperson to Fortune (29 Jan 2026): company-wide 70-90%, about 90% for Claude Code itself. Google blog 22 Apr 2026: 75% of new code is AI-generated and approved by engineers, up from 50% last fall; Semafor notes such claims are hard to fact-check and "new code" is undefined. Microsoft said 20-30% in Apr 2025. (2) Amodei, Axios 28 May 2025: AI could wipe out half of entry-level white-collar jobs and spike unemployment to 10-20% in one to five years. BLS 4 Sep 2026: unemployment 4.1%, payrolls +162,000 in August. Stanford Digital Economy Lab update (12 Aug 2026): 22-25-year-olds in AI-exposed jobs are 19% below the expected employment level, driven by reduced hiring; the authors call these early descriptive indicators and state they find no evidence of widespread economy-wide displacement; the metric differs from the earlier 13% regression estimate. NY Fed (1 Sep 2026): 4% of service firms laid off workers because of AI. (3) Altman, "Reflections", Jan 2025: "in 2025, we may see the first AI agents join the workforce and materially change the output of companies". Deloitte Tech Trends 2026 via Reworked: 11% of organisations had agents in production. Karpathy, 26 Feb 2026: coding agents basically did not work before December and basically work since. (4) Zuckerberg on Joe Rogan (Jan 2025, via Fortune): probably in 2025 an AI that can effectively be a mid-level engineer; LlamaCon 29 Apr 2025: maybe half the development done by AI within a year. TechCrunch 2 Jul 2026: he told staff agent development had not accelerated as expected. (5) Altman on X, 29 Oct 2025: internal goal of an automated AI research intern by September 2026, a true automated researcher by March 2028, "we may totally fail". OpenAI says in Sep 2026 that it reached the intern goal; nobody outside OpenAI can check. Several quotes were read via summaries; re-check against source before quoting.',
 bg=PAPER)
print('b5 ok')
